site_name: Beets Plugin Template
site_description: Documentation for the Beets Plugin Template
site_author: Your Name
site_url: https://yourusername.github.io/beets-plugin-template/

repo_name: yourusername/beets-plugin-template
repo_url: https://github.com/yourusername/beets-plugin-template

theme:
  name: material
  custom_dir: docs/overrides